### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Candlemane** [OgulcanKacarr/Simple-InstaBrute#2]
Traceback (most recent call last):
  File "/home/user/InstaBrute/InstaBrute.py", line 170, in <module>
    Attack(targetUsername.userName)
  File "/home/user/InstaBrute/InstaBrute.py", line 110, in Attack
    sendmessage("Started")
  File "/home/user/InstaBrute/InstaBrute.py", line 13, in sendmessage
    subprocess.Popen(['notify-send', message])
NameError: name 'subprocess' is not defined

**Comment by OgulcanKacarr** [comment]
solved
