### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by albatrosrkn** [OgulcanKacarr/Simple-InstaBrute#4]
Hocam merhaba.Aşağıdaki hatayı almaktayım yardımcı olursan sevinirim.

Traceback (most recent call last):                                                                                                                                   
  File "/opt/Simple-InstaBrute/InstaBrute.py", line 180, in <module>                                                                                                 
    Attack(url, wordlist)                                                                                                                                            
  File "/opt/Simple-InstaBrute/InstaBrute.py", line 114, in Attack                                                                                                   
    browser = webdriver.Firefox()                                                                                                                                    
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/firefox/webdriver.py", line 176, in __init__                                                       
    self.service.start()                                                                                                                                             
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 98, in start                                                              
    self.assert_process_still_running()                                                                                                                              
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running                                      
    raise WebDriverException(                                                                                                                                        
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64

**Comment by OgulcanKacarr** [comment]
> selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64

sürüm uyumsuzluğundan kaynaklı bir hata alıyorsun sanırsam, şuradaki çözümleri deneyebilirsin: https://stackoverflow.com/questions/70821737/webdriverexception-message-service-geckodriver-unexpectedly-exited-status-cod
